/* GraphBranch — contenido inventado de la demo (mensajes de commit, issues, comentarios).
   Es texto "de usuario", no de la interfaz, así que vive aparte de js/locales: la demo
   usa el idioma activo si está aquí y, si no, inglés. Para sumar uno, copia el bloque `en`.
   En los mensajes de commit, {s} es el ámbito (scope) de la rama. */
(function (GB) {
  'use strict';

  GB.demoContent = {
    en: {
      feature: [
        'feat({s}): first version of the component',
        'feat({s}): loading and empty states',
        'feat({s}): client-side validation',
        'feat({s}): keyboard shortcuts',
        'refactor({s}): split logic from rendering',
        'test({s}): cases for invalid input',
        'fix({s}): fix focus when the dialog closes',
        'style({s}): tweak spacing on mobile',
        'docs({s}): document the options',
        'perf({s}): memoize the totals calculation',
        'chore({s}): remove unused imports',
      ],
      fix: [
        'fix({s}): handle the empty server response',
        'fix({s}): prevent double form submission',
        'test({s}): reproduce the reported bug',
        'fix({s}): time zone in dates',
      ],
      develop: [
        'chore(deps): bump minor dependencies',
        'ci: cache node_modules between runs',
        'refactor(core): unify the HTTP client',
        'docs: update the README',
        'build: split the bundle by route',
      ],
      hotfix: ['fix(api): retry when the database is unresponsive', 'fix(auth): secure cookie in production'],
      issues: [
        'The save button does nothing in Safari',
        'Add PDF export',
        '500 error when uploading large images',
        'Session expires too quickly',
        'Improve dark mode contrast',
        'Document the webhooks API',
      ],
      comments: [
        'Can we add a test for this case?',
        "I'll review it this afternoon.",
        'Looks good, just one naming nit.',
        'Confirmed, it reproduces in production.',
      ],
      seed: {
        initial: 'chore: initial project structure',
        health: 'feat(api): /healthz health endpoint',
        install: 'docs: installation guide',
        layout: 'feat(ui): base layout with sidebar',
        userModel: 'feat(auth): user model and sessions',
        emptyPayload: 'fix(api): avoid the crash on empty payload',
        emptyPayloadPr: 'Avoid the crash on empty payload',
        sessionTests: 'test(auth): session expiry tests',
        loginForm: 'feat(login): form with validation',
        tokens: 'refactor(ui): color and typography tokens',
        oauth: 'feat(login): GitHub OAuth callback',
        darkVars: 'feat(theme): variables for dark mode',
        loginA11y: 'fix(login): accessible error message',
        darkToggle: 'feat(theme): toggle in the header',
        vite: 'chore(deps): bump vite to 6.2',
        retryAfter: 'fix(api): honor the Retry-After header',
        loginE2e: 'test(login): full flow with mocked OAuth',
        prLogin: 'Login with GitHub',
        prDark: 'Dark mode',
        prRetry: 'Honor Retry-After in the client',
        releaseNotes: 'GitHub login and a new layout',
        releaseNext: 'New stable version',
        resolved: 'Fixed in the latest version',
        amended: '(fixed)',
      },
    },

    es: {
      feature: [
        'feat({s}): primera versión del componente',
        'feat({s}): estados de carga y vacío',
        'feat({s}): validación en el cliente',
        'feat({s}): atajos de teclado',
        'refactor({s}): separa la lógica del renderizado',
        'test({s}): casos para entradas inválidas',
        'fix({s}): corrige el foco al cerrar el diálogo',
        'style({s}): ajusta espaciados en móvil',
        'docs({s}): documenta las opciones',
        'perf({s}): memoriza el cálculo de totales',
        'chore({s}): limpia imports sin uso',
      ],
      fix: [
        'fix({s}): maneja la respuesta vacía del servidor',
        'fix({s}): evita doble envío del formulario',
        'test({s}): reproduce el error reportado',
        'fix({s}): zona horaria en las fechas',
      ],
      develop: [
        'chore(deps): actualiza dependencias menores',
        'ci: cachea node_modules entre ejecuciones',
        'refactor(core): unifica el cliente HTTP',
        'docs: actualiza el README',
        'build: divide el bundle por ruta',
      ],
      hotfix: ['fix(api): reintenta cuando la base de datos no responde', 'fix(auth): cookie segura en producción'],
      issues: [
        'El botón de guardar no responde en Safari',
        'Agregar exportación a PDF',
        'Error 500 al subir imágenes grandes',
        'La sesión expira demasiado rápido',
        'Mejorar el contraste del modo oscuro',
        'Documentar la API de webhooks',
      ],
      comments: [
        '¿Podemos agregar una prueba para este caso?',
        'Lo reviso hoy en la tarde.',
        'Se ve bien, solo un detalle de nombres.',
        'Confirmo que se reproduce en producción.',
      ],
      seed: {
        initial: 'chore: estructura inicial del proyecto',
        health: 'feat(api): endpoint de salud /healthz',
        install: 'docs: guía de instalación',
        layout: 'feat(ui): layout base con barra lateral',
        userModel: 'feat(auth): modelo de usuario y sesiones',
        emptyPayload: 'fix(api): evita el crash con payload vacío',
        emptyPayloadPr: 'Evita el crash con payload vacío',
        sessionTests: 'test(auth): pruebas de expiración de sesión',
        loginForm: 'feat(login): formulario con validación',
        tokens: 'refactor(ui): tokens de color y tipografía',
        oauth: 'feat(login): callback OAuth de GitHub',
        darkVars: 'feat(theme): variables para modo oscuro',
        loginA11y: 'fix(login): mensaje de error accesible',
        darkToggle: 'feat(theme): interruptor en el encabezado',
        vite: 'chore(deps): actualiza vite a 6.2',
        retryAfter: 'fix(api): respeta el header Retry-After',
        loginE2e: 'test(login): flujo completo con OAuth simulado',
        prLogin: 'Login con GitHub',
        prDark: 'Modo oscuro',
        prRetry: 'Respeta Retry-After en el cliente',
        releaseNotes: 'Login con GitHub y layout nuevo',
        releaseNext: 'Nueva versión estable',
        resolved: 'Resuelto en la última versión',
        amended: '(corregido)',
      },
    },
  };
})(window.GB);
